
# Author : BEN SWISA
node1:
  ros__parameters:
    enc_y : 0
    enc_z : 1
    max_pwm : 100 # upper bound for motor pwm
    controller_freq : 100
    kp : [12.0000000,0.000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000] # controller constants
    ki : [14.000000,0.000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000]  
    kd : [36.000000,0.000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000,0.0000000]